### ISSUE TITLE
`lighttpd-2661-2662` fails to build

### ISSUE THREAD

**Issue by afsafzal** [squaresLab/ManyBugs#9]
```
mv -f .deps/connections.Tpo .deps/connections.Po
gcc -DHAVE_CONFIG_H -DLIBRARY_DIR="\"/usr/local/lib\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -save-temps -Wall -W -Wshadow -pedantic -std=gnu99 -MT network.o -MD -MP -MF .deps/network.Tpo -c -o network.o network.c
mv -f .deps/network.Tpo .deps/network.Po
gcc -DHAVE_CONFIG_H -DLIBRARY_DIR="\"/usr/local/lib\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -save-temps -Wall -W -Wshadow -pedantic -std=gnu99 -MT configfile.o -MD -MP -MF .deps/configfile.Tpo -c -o configfile.o configfile.c
[91mconfigfile.c: In function 'config_setup_connection':
[0m
[91mconfigfile.c:329:11: error: 'specific_config' has no member named 'ssl_ctx'
  PATCH(ssl_ctx);
           ^
[0m
[91mconfigfile.c:329:23: error: 'specific_config' has no member named 'ssl_ctx'
  PATCH(ssl_ctx);
                       ^
[0m
[91mconfigfile.c: In function 'config_patch_connection':
[0m
[91mconfigfile.c:389:14: error: 'specific_config' has no member named 'ssl_ctx'
     PATCH(ssl_ctx);
              ^
configfile.c:389:26: error: 'specific_config' has no member named 'ssl_ctx'
     PATCH(ssl_ctx);
                          ^
[0m
make[4]: Leaving directory `/experiment/src/src'
[91mmake[4]: *** [configfile.o] Error 1
[0m
[91mmake[3]: *** [all-recursive] Error 1
[0m
make[3]: Leaving directory `/experiment/src/src'
[91mmake[2]: *** [all] Error 2
[0m
make[2]: Leaving directory `/experiment/src/src'
[91mmake[1]: *** [all-recursive] Error 1
[0m
make[1]: Leaving directory `/experiment/src'
[91mmake: *** [all] Error 2
[0m
[91mTraceback (most recent call last):
  File "./preprocess", line 35, in <module>
[0m
[91m    subprocess.check_call('make clean && make', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
[0m
[91m    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make clean && make' returned non-zero exit status 2
[0m
Traceback (most recent call last):
  File "/home/afsoon/BugZoo/bin/bugzoo", line 9, in <module>
    load_entry_point('bugzoo==1.1.4', 'console_scripts', 'bugzoo')()
  File "/home/afsoon/BugZoo/lib/python3.5/site-packages/bugzoo/cli.py", line 524, in main
    args.func(args)
  File "/home/afsoon/BugZoo/lib/python3.5/site-packages/bugzoo/cli.py", line 486, in <lambda>
    cmd.set_defaults(func=lambda args: build_bug(rbox, args.bug, args.force))
  File "/home/afsoon/BugZoo/lib/python3.5/site-packages/bugzoo/cli.py", line 94, in build_bug
    bug.build(force=force)
  File "/home/afsoon/BugZoo/lib/python3.5/site-packages/bugzoo/bug.py", line 309, in build
    self.__build_instructions.build(force=force, quiet=quiet)
  File "/home/afsoon/BugZoo/lib/python3.5/site-packages/bugzoo/build.py", line 230, in build
    raise ImageBuildFailed(self.tag, log)
bugzoo.errors.ImageBuildFailed: squareslab/manybugs:lighttpd-2661-2662
```

**Comment by ChrisTimperley** [comment]
@afsafzal can you try to debug by installing the `openssl-dev` package? The error looks rather similar to this one: https://github.com/wg/wrk/issues/67

**Comment by afsafzal** [comment]
installing `openssl` or `libssl-dev` didn't fix the issue.

**Comment by ChrisTimperley** [comment]
Interestingly, I tried to recompile this particular bug scenario on the original ManyBugs VM and got the same error:

```
$ make distclean
$ ./configure
$ make
...
mv -f .deps/response.Tpo .deps/response.Po
gcc -DHAVE_CONFIG_H -DLIBRARY_DIR="\"/usr/local/lib\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT request.o -MD -MP -MF .deps/request.Tpo -c -o request.o request.c
configfile.c: In function ‘config_setup_connection’:
configfile.c:329: error: ‘specific_config’ has no member named ‘ssl_ctx’
configfile.c:329: error: ‘specific_config’ has no member named ‘ssl_ctx’
configfile.c: In function ‘config_patch_connection’:
configfile.c:389: error: ‘specific_config’ has no member named ‘ssl_ctx’
configfile.c:389: error: ‘specific_config’ has no member named ‘ssl_ctx’
make[4]: *** [configfile.o] Error 1
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/proc_open-buffer.Tpo .deps/proc_open-buffer.Po
mv -f .deps/network.Tpo .deps/network.Po
mv -f .deps/connections.Tpo .deps/connections.Po
mv -f .deps/server.Tpo .deps/server.Po
mv -f .deps/request.Tpo .deps/request.Po
mv -f .deps/configparser.Tpo .deps/configparser.Po
mv -f .deps/lemon.Tpo .deps/lemon.Po
make[4]: Leaving directory `/root/genprog-many-bugs/lighttpd-bug-2661-2662/lighttpd/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/root/genprog-many-bugs/lighttpd-bug-2661-2662/lighttpd/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/genprog-many-bugs/lighttpd-bug-2661-2662/lighttpd/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/genprog-many-bugs/lighttpd-bug-2661-2662/lighttpd'
make: *** [all] Error 2
```

**Comment by joerenzullo** [comment]
I just ran into this bug today and have the same trace as @afsafzal.

Tried installing libssl-dev to the base image (and committing it so that the child images would have the libraries) to no avail. I also tried installing the libraries from within the partially-built image to the same result.

I'd really like to get this particular bug working, since previous work has showed a repair for it and the bug type (segfault) is compelling.

**Comment by ChrisTimperley** [comment]
It would seem that this particular scenario requires a slightly different set of configuration flags than the others. The following commands cause the bug to successfully compile on the ManyBugs VM:

```
$ make distclean
$ ./configure --with-ldap --with-bzip2 --with-openssl --with-gdbm --with-memcache --with-webdav-props --with-webdav-locks
$ make
```

I'll incorporate them into the Docker file for the scenario.

**Comment by ChrisTimperley** [comment]
After installing the missing dependencies, and executing `configure` with the appropriate flags, the scenario builds successfully inside the Docker container.

I'm adding the ability to pass additional flags to `configure` inside the `preprocess` script. Once that's done, the issue should be fully addressed.

**Comment by joerenzullo** [comment]
Thanks, @ChrisTimperley !
